# Generated by Django 3.0.7 on 2020-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.TimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
