# Generated by Django 3.0.7 on 2020-06-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200614_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_time',
        ),
    ]
