# Generated by Django 3.0.7 on 2020-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'vendor'), (3, 'administrator')], default=1),
        ),
    ]
