# Generated by Django 3.0.7 on 2020-06-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendor_profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='calendar',
            field=models.ManyToManyField(to='engine.TimeSlot'),
        ),
    ]
