# Generated by Django 3.0.7 on 2020-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendor_profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='calendar',
            field=models.ManyToManyField(to='calendar_app.OpenInCalendar'),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='time_gap_in_mins',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='vendor_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
