# Generated by Django 3.0.7 on 2020-06-28 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_timeslotforvendor'),
        ('accounts', '0002_auto_20200618_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_profile',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.TimeSlotForVendor'),
        ),
    ]
