# Generated by Django 3.0.7 on 2020-07-18 05:18

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_profile_timeslot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='timeslot',
            field=models.IntegerField(default=1),
        ),
    ]
