# Generated by Django 3.0.7 on 2020-07-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200718_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'vendor'), (3, 'administrator')], default=1, null=True),
        ),
    ]
