# Generated by Django 3.0.7 on 2020-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200718_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
