# Generated by Django 3.0.7 on 2020-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200718_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_profile',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='administrator_profile',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
