# Generated by Django 3.0.7 on 2020-06-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200618_0807'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer_profile')),
                ('datetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.TimeSlot')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor_profile')),
            ],
        ),
    ]
