# Generated by Django 3.0.7 on 2020-06-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotForVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('interval', models.IntegerField()),
            ],
        ),
    ]
